{
 "title": "metal-api",
 "tags": [ "metal-stack" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Replicas",
   "type": "stat",
   "description": "The number of metal-api replicas.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"metal-api\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=\"metal-api\"})",
     "legendFormat": "stack"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"metal-api\"})",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=\"metal-api\"})",
     "legendFormat": "heap"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"metal-api\"})",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"metal-api.*\"}[5m]))",
     "legendFormat": "cpu usage seconds"
    }
   ]
  },
  {
   "title": "HTTP Codes",
   "type": "timeseries",
   "description": "Return codes of the HTTP responses of the metal-api.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(metal_api_requests_total[$__interval])) by(code, method) ",
     "legendFormat": "{{ method }}: {{ code }}"
    }
   ]
  },
  {
   "title": "HTTP duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(metal_api_request_duration_seconds_sum[$__interval])) by (route)",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{app=\"metal-api\"}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{app=\"metal-api\"} != \"finished streaming call with code Internal\" | json | level=\"error\" "
    }
   ]
  },
  { "title": "Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Machines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metal_partition_capacity_total{job=\"metal-metrics-exporter\"})"
    }
   ]
  },
  {
   "title": "Free Machines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metal_partition_capacity_free{job=\"metal-metrics-exporter\"})"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metal_partition_capacity_allocated{job=\"metal-metrics-exporter\"})"
    }
   ]
  },
  {
   "title": "Faulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metal_partition_capacity_faulty{job=\"metal-metrics-exporter\"})"
    }
   ]
  },
  {
   "title": "Firewalls",
   "type": "stat",
   "description": "Machines with a firewall role.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metal_machine_allocation_info{role=\"firewall\"})"
    }
   ]
  },
  {
   "title": "Machines",
   "type": "stat",
   "description": "Machines with a machine role.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metal_machine_allocation_info{role=\"machine\"})"
    }
   ]
  },
  {
   "title": "Machine Issues",
   "type": "bargauge",
   "description": "Accumulated number of machine issues.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (issueid) (metal_machine_issues)",
     "legendFormat": "{{issueid}}"
    }
   ]
  },
  { "title": "Switches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "metal-core up",
   "type": "stat",
   "description": "metal-core instances that are up.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metal_switch_metal_core_up != 0)"
    }
   ]
  },
  {
   "title": "metal-core down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metal_switch_metal_core_up) == 0"
    }
   ]
  },
  {
   "title": "Sync Durations",
   "type": "timeseries",
   "description": "Sync durations of metal-core in milliseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(metal_switch_sync_durations_ms) by (switchname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Failed",
   "type": "timeseries",
   "description": "Sync failures of metal-core.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(metal_switch_sync_failed) by (switchname)",
     "legendFormat": "{{switchname}}"
    }
   ]
  }
 ]
}