{
 "title": "Rethinkdb",
 "tags": [ "metal-stack" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server_var",
    "label": "Server",
    "query": {
     "query": "label_values(server_client_connections{job=\"rethinkdb-exporter\"},server)"
    }
   },
   {
    "name": "db_var",
    "label": "Database",
    "query": {
     "query": "label_values(table_docs_per_second{job=\"rethinkdb-exporter\"},db)"
    }
   },
   {
    "name": "table_var",
    "label": "Table",
    "query": {
     "query": "label_values(table_docs_per_second{job=\"rethinkdb-exporter\"}, table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Stats collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stat collection duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_latency{job=\"rethinkdb-exporter\"}",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Stat collection errors count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scrape_errors{job=\"rethinkdb-exporter\"}",
     "legendFormat": "errors count"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Docs per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cluster_docs_per_second{job=\"rethinkdb-exporter\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Cluster client connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cluster_client_connections{job=\"rethinkdb-exporter\"}",
     "legendFormat": "connections count"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "server_queries_per_second{server=~\"$server_var\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server client connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "server_client_connections{server=~\"$server_var\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server Docs per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "server_docs_per_second{server=~\"$server_var\"}",
     "legendFormat": "{{server}}::{{operation}}"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table Docs per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "table_docs_per_second{db=~\"$db_var\", table=~\"$table_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}"
    }
   ]
  },
  {
   "title": "Table replica Docs per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tablereplica_docs_per_second{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}::{{server}}"
    }
   ]
  },
  {
   "title": "Table Rows count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "table_rows_count{db=~\"$db_var\", table=~\"$table_var\"}",
     "legendFormat": "{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table replica Cache bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tablereplica_cache_bytes{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{server}}"
    }
   ]
  },
  {
   "title": "Table replica disk io bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tablereplica_io{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}::{{server}}"
    }
   ]
  },
  {
   "title": "Table replica Disk data bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tablereplica_data_bytes{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{server}}"
    }
   ]
  }
 ]
}