applicationDict: true
default:
  valueFiles:
  - values-kubrix-default.yaml
  - values-cluster-kind.yaml
  - values-customer-generated.yaml
  - values-customer.yaml
applications:
  prometheus-blackbox-exporter:
    enabled: true
  loki:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: '-1'
  grafana:
    enabled: true
  mimir:
    enabled: true
  tempo:
    enabled: true
  testkube:
    enabled: true
  team-onboarding:
    enabled: true
