applicationDict: true
default:
  valueFiles:
  - values-kubrix-default.yaml
  - values-cluster-kind.yaml
applications:
  traefik:
    enabled: false
  openbao:
    enabled: false
  cnpg:
    enabled: false
  cert-manager:
    annotations:
      argocd.argoproj.io/sync-wave: '-3'
  argocd:
    annotations:
      argocd.argoproj.io/sync-wave: '-2'
  k8s-monitoring:
    annotations:
      argocd.argoproj.io/sync-wave: '-1'
  crossplane:
    annotations:
      argocd.argoproj.io/sync-wave: '-1'
  grafana:
    enabled: true
  mimir:
    enabled: true
  loki:
    enabled: true
  tempo:
    enabled: true
  falco:
    enabled: true
  external-secrets:
    annotations: null
  keycloak:
    annotations: null
  kargo:
    enabled: true
  kubecost:
    enabled: true
  argo-rollouts:
    enabled: true
  kyverno:
    enabled: true
  backstage:
    enabled: true
  team-onboarding:
    enabled: true
