applicationDict: true
default:
  valueFiles:
  - values-kubrix-default.yaml
  - values-provider-metalstack.yaml
  - values-demo-metalstack.yaml
applications:
  external-dns:
    enabled: true
    valueFiles:
    - values-dns-ionos.yaml
  prometheus-blackbox-exporter:
    enabled: true
  loki:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: '-1'
  kargo:
    enabled: true
  argo-rollouts:
    enabled: true
  grafana:
    enabled: true
  mimir:
    enabled: true
  falco:
    enabled: true
  kyverno:
    enabled: true
  kubevirt-manager:
    enabled: true
  kubevirt:
    enabled: true
  velero:
    enabled: true
  minio:
    enabled: true
  backstage:
    enabled: true
  team-onboarding:
    enabled: true
