applicationDict: true
default:
  valueFiles:
  - values-kubrix-default.yaml
  - values-cluster-kind.yaml
  - values-customer-generated.yaml
  - values-customer.yaml
applications:
  kargo:
    enabled: true
  argo-rollouts:
    enabled: true
  testkube:
    enabled: true
  backstage:
    enabled: true
  team-onboarding:
    enabled: true
