minio:
  enabled: true
  replicas: 1
  mode: standalone  
  persistence:
    size: 20Gi
  resources:
    requests:
      memory: 1Gi
  buckets:
    - name: velero
      policy: public
      purge: false
  metrics:
    serviceMonitor:
      enabled: true
      includeNode: true
  existingSecret: minio-admin-secret
  users:
    - accessKey: minio
      existingSecret: minio-admin-secret
      existingSecretKey: secretKey
      policy: consoleAdmin
  tls:
    enabled: false
    certSecret: "minio-server-tls"
    publicCrt: tls.crt
    privateKey: tls.key
  consoleIngress:
    enabled: true
    annotations:
      route.openshift.io/termination: edge   
      cert-manager.io/cluster-issuer: letsencrypt-staging-cip  
    path: /
    hosts:
      - minio-console.apps.cluster1.mcp.pitagora.at
    tls: 
      - secretName: minio-console-tls
        hosts:
          - minio-console.apps.cluster1.mcp.pitagora.at
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      route.openshift.io/termination: edge   
    path: /
    hosts:
      - minio.apps.cluster1.mcp.pitagora.at
    tls: 
      - secretName: minio-server-tls
        hosts:
          - minio.apps.cluster1.mcp.pitagora.at