apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: argocd-probe
spec:
  interval: 60s
  module: https_2xx_insecure
  prober:
    path: /probe
    url: sx-prometheus-blackbox-exporter.prometheus-blackbox-exporter.svc:9115
  targets:
    staticConfig:
      labels:
        platform: kubrix
        service: argocd
      static:
        - https://{{ index .Values "argo-cd" "global" "domain" }}/healthz
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-kubrix-service-status
  namespace: mimir
  labels:
    platform: kubrix
    service: argocd
spec:
  groups:
  - name: kubrix.service.status
    interval: 30s
    rules:
    # --- Argo CD ---
    - record: kubrix_service_status
      labels:
        platform: kubrix
        service: argocd
      expr: |
        (
          2 * (scalar(min(probe_success{platform="kubrix",service="argocd"})) == bool 0)
        )
        +
        (
          scalar(max(GRAFANA_ALERTS{namespace="argocd"} == bool 1) or vector(0))
          *
          (1 - (scalar(min(probe_success{platform="kubrix",service="argocd"})) == bool 0))
        )
