{
 "title": "GRC/OpenBao",
 "description": "Openbao Metrics maintained by suXess team",
 "tags": [
  "openbao",
  "vault",
  "grc",
  "suXess"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(up{job=\"sx-openbao-active\"},instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(up{job=\"sx-openbao-active\", instance=~\"$node:(.*)\"},instance)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": {
     "query": "query_result(label_replace(  label_replace(    label_replace(      vault_secret_kv_count,      \"mount_point\", \"${1}_$2\", \"mount_point\", \"(.*)-(.+)\"    ),    \"mount_point\", \"${1}_$2\", \"mount_point\", \"(.*)-(.+)\"  ),  \"mount_point\", \"${1}_$2\", \"mount_point\", \"(.*)-(.+)\"))"
    }
   },
   { "name": "interval", "label": "Interval", "query": "5m" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (job) (up{job=\"sx-openbao-active\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(1 + vault_core_unsealed{})", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "KV Engines",
   "type": "stat",
   "description": "Number of KV Engines across namespaces",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vault_secret_kv_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Identity Entities",
   "type": "stat",
   "description": "Number of Identity Entities",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities)"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vault_identity_entity_alias_count)",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "Autopilot Overall Health",
   "type": "timeseries",
   "description": "Indicates whether all nodes are healthy",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "vault_autopilot_healthy", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Cluster Health per Node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_autopilot_node_healthy{container=~\"vault\"}) by (node_id)\n",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Failure Tolerance",
   "type": "timeseries",
   "description": "The failure tolerance indicates how many currently healthy nodes can fail without losing quorum.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "vault_autopilot_failure_tolerance",
     "legendFormat": "failure tolerance"
    }
   ]
  },
  {
   "title": "Secrets per KV Engine",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance,pod) (vault_secret_kv_count)",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Entity Methods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance)(vault_identity_entity_alias_count)"
    }
   ]
  },
  {
   "title": "Vault and Raft Leadership",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Leader Node",
     "type": "stat",
     "description": "Last reported Raft leader node",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "vault_raft_state_leader" }
     ]
    },
    {
     "title": "Follower Last Heartbeat",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(vault_raft_storage_follower_last_heartbeat_ms) by (peer_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft Leader Last Contact (ms)",
     "type": "timeseries",
     "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_leader_lastContact_sum[$interval]) / rate(vault_raft_leader_lastContact_count[$interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Raft Integrated Storage Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Performance (ms)",
     "type": "timeseries",
     "description": "Performance of Raft Integrated Storage Backend",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_storage_delete_sum[$interval]) / rate(vault_raft_storage_delete_count[$interval]))",
       "legendFormat": "AVG DEL"
      },
      {
       "expr": "sum(rate(vault_raft_storage_list_sum[$interval]) / rate(vault_raft_storage_list_count[$interval]))",
       "legendFormat": "AVG LIST"
      },
      {
       "expr": "sum(rate(vault_raft_storage_get_sum[$interval]) / rate(vault_raft_storage_get_count[$interval]))",
       "legendFormat": "AVG GET"
      },
      {
       "expr": "sum(rate(vault_raft_storage_put_sum[$interval]) / rate(vault_raft_storage_put_count[$interval]))",
       "legendFormat": "AVG PUT"
      }
     ]
    },
    {
     "title": "Time Spent (ms)",
     "type": "bargauge",
     "description": "Sum of time spent to perform actions on the storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(vault_raft_storage_delete_sum)",
       "legendFormat": "DEL"
      },
      {
       "expr": "avg(vault_raft_storage_list_sum)",
       "legendFormat": "LIST"
      },
      {
       "expr": "avg(vault_raft_storage_get_sum)",
       "legendFormat": "GET"
      },
      {
       "expr": "avg(vault_raft_storage_put_sum)",
       "legendFormat": "PUT"
      }
     ]
    },
    {
     "title": "Mount Table Entries",
     "type": "timeseries",
     "description": "Mountpoint count metrics include labels to indicate whether the relevant table is an authentication table or a logical table and whether the table is replicated or local",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(vault_core_mount_table_num_entries) by (type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mount Table Size",
     "type": "timeseries",
     "description": "Table size metrics include labels to indicate whether the relevant table is an authentication table or a logical table and whether the table is replicated or local.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(vault_core_mount_table_size) by (type,local)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/Mem Info: $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap Objects Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_heap_objects{} / vault_runtime_malloc_count{})"
      }
     ]
    },
    {
     "title": "Number of Goroutines",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_num_goroutines{})"
      }
     ]
    },
    {
     "title": "Allocated MB",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(vault_runtime_alloc_bytes{})",
       "legendFormat": "$node"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "vault_runtime_total_gc_pause_ns",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "vault_runtime_sys_bytes", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Token",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Available Tokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "avg(vault_token_count)" }
     ]
    },
    {
     "title": "Tokens by Policy",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 5 },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_policy)",
       "legendFormat": "{{ policy }}"
      }
     ]
    },
    {
     "title": "Pending Tokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_token_create_count - vault_token_store_count)"
      }
     ]
    },
    {
     "title": "Tokens by TTL",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "avg without(instance,pod) (vault_token_count_by_ttl)",
       "legendFormat": "{{ creation_ttl }}"
      }
     ]
    },
    {
     "title": "Tokens by Auth Method",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "avg without(instance,pod) (vault_token_count_by_auth)",
       "legendFormat": "{{ auth_method }}"
      }
     ]
    },
    {
     "title": "Tokens Creation by Method & TTL",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(auth_method, creation_ttl) (vault_token_creation)",
       "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
      }
     ]
    },
    {
     "title": "Token Creation/Storage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_create_count)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg without(instance) (vault_token_store_count)",
       "legendFormat": "Store"
      }
     ]
    },
    {
     "title": "Token Lookups",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_token_lookup_count[1m]))",
       "legendFormat": "Lookups"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Log Request Failures",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_request_failure[1m]))",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Log Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 3, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_audit_log_request_count[1m]))",
       "legendFormat": "Request "
      },
      {
       "expr": "avg(irate(vault_audit_log_response_count[1m]))",
       "legendFormat": "Response"
      },
      {
       "expr": "avg(irate(vault_core_handle_request_count[1m]))",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "Log Audit Sink Succes",
     "type": "stat",
     "description": "Number of times an audit device was written to successfully",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_sink_success[1m]))",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Log Response Failures",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_response_failure[1m]))",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Policy Set",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_policy_set_policy_count[1m]))",
       "legendFormat": "SET"
      }
     ]
    },
    {
     "title": "Policy Get",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_policy_get_policy_count[1m]))",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "Configured Policies",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vault_policy_configured_count) by (policy_type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "mountpoint",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      },
      {
       "expr": "avg(rate(vault_route_rollback_${mountpoint}__sum[1m]) / rate(vault_route_rollback_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Rollback"
      }
     ]
    }
   ]
  },
  {
   "title": "unused for internal storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Handle Requests",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(vault_core_handle_request) by (quantile)",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Vault Leadership Setup Failures",
     "type": "stat",
     "description": "Number of Vault cluster leadership setup failures. Failures indicate bad overall cluster leadership status.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "vault_core_leadership_setup_failed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vault Leadership Lost Count",
     "type": "stat",
     "description": "Any count greater than zero means that Vault experienced a leadership change.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      { "expr": "vault_core_leadership_lost", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Vault Raft Leader Elections",
     "type": "stat",
     "description": "Increments whenever raft server starts an election. If there are frequent elections or leadership changes, it would likely indicate network issues between the raft nodes, or that the raft servers themselves are unable to keep up with the load.",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(vault_raft_state_candidate)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Raft Follower State Entered Count ",
     "type": "bargauge",
     "description": "Number of times node has entered the follower mode. This happens when a new node joins the cluster or after the end of a leader election.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      { "expr": "vault_raft_state_follower", "legendFormat": "{{ host }}" }
     ]
    }
   ]
  }
 ]
}