{
 "title": "GRC/Velero",
 "description": "Velero Stats maintained by Velero team",
 "tags": [
  "velero",
  "grc",
  "suXess"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(velero_backup_attempt_total,cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"velero\", cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total, schedule)"
    }
   },
   {
    "name": "csi_backup_name",
    "query": {
     "query": "label_values(velero_csi_snapshot_attempt_total, backupName)"
    }
   },
   {
    "name": "restic_node",
    "query": {
     "query": "label_values(restic_pod_volume_backup_enqueue_count, node)"
    }
   },
   {
    "name": "restic_backup_name",
    "query": {
     "query": "label_values(restic_restic_operation_latency_seconds_gauge, backupName)"
    }
   },
   {
    "name": "restic_operation",
    "query": {
     "query": "label_values(restic_restic_operation_latency_seconds_gauge, operation)"
    }
   },
   {
    "name": "restic_pvb_name",
    "query": {
     "query": "label_values(restic_restic_operation_latency_seconds_gauge, pod_volume_backup)"
    }
   },
   {
    "name": "fsb_node",
    "query": {
     "query": "label_values(podVolume_pod_volume_backup_enqueue_count, node)"
    }
   },
   {
    "name": "fsb_backup_name",
    "query": {
     "query": "label_values(podVolume_pod_volume_operation_latency_seconds_gauge, backupName)"
    }
   },
   {
    "name": "fsb_operation",
    "query": {
     "query": "label_values(podVolume_pod_volume_operation_latency_seconds_gauge, operation)"
    }
   },
   {
    "name": "fsb_pvb_name",
    "query": {
     "query": "label_values(podVolume_pod_volume_operation_latency_seconds_gauge, pod_volume_backup)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_active_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Volume snapshot Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}) / sum(velero_volume_snapshot_attempt_total{schedule=~\"$schedule\"})\n"
    }
   ]
  },
  {
   "title": "Backup Deletion Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_deletion_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_deletion_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Hours since last Backup",
   "type": "table",
   "description": "for schedule backup use only",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule!=\"\"}) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "velero_backup_total{cluster=~\"$cluster\"}",
     "legendFormat": "Backup Total - {{cluster}}"
    }
   ]
  },
  {
   "title": "Backup overview per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(velero_backup_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup success"
    },
    {
     "expr": "round(sum(increase(velero_backup_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup partial failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion success"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion failure"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_total{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items total"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_errors{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items errors_total"
    },
    {
     "expr": "round(sum(increase(velero_backup_validation_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup validation failure"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot success"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_warning_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup warning"
    }
   ]
  },
  {
   "title": "Backup time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\",le!=\"+Inf\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Tarball Backup Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(velero_backup_tarball_size_bytes{schedule=~\"$schedule\"}[15m]))",
     "legendFormat": "tarball - {{schedule}}"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_tarball_size_bytes{schedule=~\".*\"}[15m]))",
     "legendFormat": "tarball"
    }
   ]
  },
  {
   "title": "Restore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Restore",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(velero_restore_attempt_total{cluster=~\"$cluster\"}[$__interval])) by (cluster) / sum(rate(velero_restore_success_total{cluster=~\"$cluster\"}[$__interval])) by (cluster)",
     "legendFormat": " {{cluster}}"
    }
   ]
  },
  {
   "title": "Restore Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_restore_success_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}) by (cluster) / sum(velero_restore_attempt_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Restore Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "avg_over_time(velero_restore_total{cluster=~\"$cluster\"}[15m])",
     "legendFormat": "{{label_name}}Restore Total -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_success_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Success Total - {{schedule}} -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_success_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": " Restore Partial Failure Total - {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_partial_failure_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Partial Failure Total -  {{schedule}} - {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_partial_failure_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Partial Failure Total -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_failed_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Failure Total - {{schedule}} -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_failed_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Failure Total -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_validation_failed_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Validation Failed - {{schedule}} -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_validation_failed_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Validation Failed -  {{cluster}}"
    }
   ]
  },
  { "title": "Kopia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Kopia",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kopia_blob_upload_bytes_total{pod=~\"$pod\"}",
     "legendFormat": "blob upload - {{pod}}"
    },
    {
     "expr": "kopia_content_write_bytes_total{pod=~\"$pod\"}",
     "legendFormat": "write total - {{pod}}"
    },
    {
     "expr": "kopia_content_read_bytes_total{pod=~\"$pod\"}",
     "legendFormat": "read total - {{pod}}"
    },
    {
     "expr": "kopia_content_encrypted_bytes_total{pod=~\"$pod\"}",
     "legendFormat": "ecrypted - {{pod}}"
    },
    {
     "expr": "kopia_content_after_compression_bytes_total{pod=~\"$pod\"}",
     "legendFormat": "after compression - {{pod}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(kopia_blob_storage_latency_ms_sum[$__rate_interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kopia_blob_download_full_blob_bytes_total[$__rate_interval])",
     "legendFormat": "Full blob"
    },
    {
     "expr": "rate(kopia_blob_download_partial_blob_bytes_total[$__rate_interval])",
     "legendFormat": "Partial Blob"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kopia_cache_hit_total) by (cache)",
     "legendFormat": "hit {{cache}}"
    },
    {
     "expr": "sum(kopia_cache_miss_total * -1) by (cache)",
     "legendFormat": "miss {{cache}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(kopia_cache_store_errors_total) by (cache)",
     "legendFormat": "cache store errors  - {{cache}}"
    },
    {
     "expr": "sum(kopia_cache_miss_errors_total) by (cache)",
     "legendFormat": "cache miss errors - {{cache}}"
    },
    {
     "expr": "sum(kopia_blob_errors_total) by (method)",
     "legendFormat": "blob errors - {{method}}"
    },
    {
     "expr": "sum(kopia_content_get_not_found_count_total)",
     "legendFormat": "Not found"
    },
    {
     "expr": "sum(kopia_content_get_error_count_total)",
     "legendFormat": "error count total"
    },
    {
     "expr": "sum(kopia_cache_malformed_total)",
     "legendFormat": "cache malformed"
    }
   ]
  },
  {
   "title": "Uploaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kopia_content_uploaded_bytes_total[$__rate_interval])",
     "legendFormat": "Uploaded"
    },
    {
     "expr": "rate(kopia_content_hashed_bytes_total[$__rate_interval])",
     "legendFormat": "Hashed"
    },
    {
     "expr": "rate(kopia_content_compression_attempted_bytes_total[$__rate_interval])",
     "legendFormat": "Pre compressed"
    },
    {
     "expr": "rate(kopia_content_non_compressible_bytes_total[$__rate_interval])",
     "legendFormat": "Non compressed"
    },
    {
     "expr": "rate(kopia_content_compression_savings_bytes_total[$__rate_interval])",
     "legendFormat": "Compressed"
    },
    {
     "expr": "rate(kopia_content_deduplicated_bytes_total[$__rate_interval])",
     "legendFormat": "Deduplicated"
    }
   ]
  },
  {
   "title": "Data Mover",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CSI Snapshot Data Mover per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(podVolume_data_upload_success_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data upload success"
    },
    {
     "expr": "round(sum(increase(podVolume_data_upload_failure_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data upload failure"
    },
    {
     "expr": "round(sum(increase(podVolume_data_upload_cancel_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data upload cancel"
    },
    {
     "expr": "round(sum(increase(podVolume_data_download_success_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data download success"
    },
    {
     "expr": "round(sum(increase(podVolume_data_download_failure_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data download failure"
    },
    {
     "expr": "round(sum(increase(podVolume_data_upload_cancel_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data download cancel"
    }
   ]
  },
  {
   "title": "CSI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CSI per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(velero_csi_snapshot_attempt_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot attempt"
    },
    {
     "expr": "round(sum(increase(velero_csi_snapshot_success_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot success"
    },
    {
     "expr": "round(sum(increase(velero_csi_snapshot_failure_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot failure"
    }
   ]
  },
  {
   "title": "Restic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Restic Success Rate",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(restic_pod_volume_backup_dequeue_count{node=~\"$restic_node\"}) / sum(restic_pod_volume_backup_enqueue_count{node=~\"$restic_node\"})"
      }
     ]
    },
    {
     "title": "Restic per hour",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 20, "x": 4, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum(increase(restic_pod_volume_backup_enqueue_count{node=~\"$restic_node\"}[1h])))",
       "legendFormat": "Restic enqueue"
      },
      {
       "expr": "round(sum(increase(restic_pod_volume_backup_dequeue_count{node=~\"$restic_node\"}[1h])))",
       "legendFormat": "Restic dequeue"
      }
     ]
    },
    {
     "title": "Restic time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(restic_restic_operation_latency_seconds_gauge{backupName=~\"$restic_backup_name\", node=~\"$restic_node\", operation=~\"$restic_operation\", pod_volume_backup=~\"$restic_pvb_name\"}[15m]))",
       "legendFormat": "Avg over time"
      }
     ]
    }
   ]
  },
  {
   "title": "File System Backup(for v1.10 and later)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "FSB Success Rate",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(podVolume_pod_volume_backup_dequeue_count{node=~\"$fsb_node\"}) / sum(podVolume_pod_volume_backup_enqueue_count{node=~\"$fsb_node\"})"
      }
     ]
    },
    {
     "title": "FSB per hour",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 20, "x": 4, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum(increase(podVolume_pod_volume_backup_enqueue_count{node=~\"$fsb_node\"}[1h])))",
       "legendFormat": "FSB enqueue"
      },
      {
       "expr": "round(sum(increase(podVolume_pod_volume_backup_dequeue_count{node=~\"$fsb_node\"}[1h])))",
       "legendFormat": "FSB dequeue"
      }
     ]
    },
    {
     "title": "FSB time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(podVolume_pod_volume_operation_latency_seconds_gauge{backupName=~\"$fsb_backup_name\", node=~\"$fsb_node\", operation=~\"$fsb_operation\", pod_volume_backup=~\"$fsb_pvb_name\"}[15m]))",
       "legendFormat": "Avg over time"
      }
     ]
    }
   ]
  }
 ]
}