argo-cd:
  global:
    domain: argocd.apps.cluster1.mcp.pitagora.at

  configs:
    params:
      server.insecure: true
      application.namespaces: "adn-*"
      applicationsetcontroller.namespaces: "adn-*"
      applicationsetcontroller.allowed.scm.providers: https://github.com/
    secret:
      createSecret: false

    cm:
      application.resourceTrackingMethod: annotation
      accounts.backstage: apiKey

      resource.customizations: |
        argoproj.io/Application:
          health.lua: |
            hs = {}
            hs.status = "Progressing"
            hs.message = ""
            if obj.status ~= nil then
              if obj.status.health ~= nil then
                hs.status = obj.status.health.status
                if obj.status.health.message ~= nil then
                  hs.message = obj.status.health.message
                end
              end
            end
            return hs

    rbac:
      policy.csv: |
        p, backstage, applications, get, */*, allow

  server:
    ingress:
      ingressClassName: nginx
      enabled: true
      annotations: 
        route.openshift.io/termination: edge   

    extensions:
      enabled: true
      contents:
        - name: argo-rollouts
          url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.4/extension.tar

  applicationSet:
    allowAnyNamespace: true
