grafanaFolder: "kubriX"

keycloak:
  mode: production
  fullnameOverride: kubrix-keycloak-service

  image:
    tag: "26.6.1"

  admin:
    existingSecret: keycloak-admin
    existingSecretUsernameKey: admin-username
    existingSecretPasswordKey: admin-password

  hostname:
    strict: false
    backchannelDynamic: true

  proxy:
    headers: xforwarded

  database:
    external:
      vendor: postgres
      host: "sx-keycloak-cluster-rw.keycloak.svc.cluster.local"
      port: 5432
      name: postgres
      username: keycloak
      existingSecret: cp-keycloak-externaldb-secret
      existingSecretPasswordKey: POSTGRES_PASSWORD
      pool:
        initialSize: 2
        minSize: 2
        maxSize: 20
    transaction:
      xaEnabled: false

  ingress:
    public:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/ttl: "60"
        cert-manager.io/cluster-issuer: default-issuer

  probes:
    readiness:
      periodSeconds: 5
      failureThreshold: 5
    liveness:
      periodSeconds: 20
      failureThreshold: 5
    startup:
      periodSeconds: 5
      failureThreshold: 20

  resources:
    requests:
      memory: "512Mi"
      cpu: "150m"
    limits:
      memory: "1Gi"
      cpu: "1"

  networkPolicy:
    enabled: false

  features:
    enabled:
      - authorization
    disabled:
      - step-up-authentication

  health:
    enabled: true

  metrics:
    enabled: true
    userEvents: true
    cacheHistograms: true
    serviceMonitor:
      enabled: true

  logging:
    console:
      output: json

  extraEnv:
    - name: KC_LOG_CONSOLE_COLOR
      value: "true"
    - name: KC_HTTP_METRICS_HISTOGRAMS_ENABLED
      value: "true"
    - name: KC_HTTP_METRICS_SLOS
      value: "5,10,25,50,250,500,1000,2500,5000,10000"
    - name: KC_EVENT_METRICS_USER_TAGS
      value: "realm,idp,clientId"

#### kubrix
kubrix:
  keycloak:
    domainName: ~
    realm:
      realmid: kubrix
      users: []
      groups:
        - name: backstage-admin # for service-account permission workaround
    # start with 2FA mobile Authenticators
    mfa:
      enabled: false

crossplane:
  activeMRDs:
    authbackends.jwt.vault.upbound.io: true
    realms.realm.keycloak.crossplane.io: true
    authbackendroles.jwt.vault.upbound.io: true
    protocolmappers.client.keycloak.crossplane.io: true
    roles.role.keycloak.crossplane.io: true
    roles.group.keycloak.crossplane.io: true
    groups.group.keycloak.crossplane.io: true
    users.user.keycloak.crossplane.io: true
    clientscopes.openidclient.keycloak.crossplane.io: true
    clientdefaultscopes.openidclient.keycloak.crossplane.io: true
    clients.openidclient.keycloak.crossplane.io: true
    memberships.group.keycloak.crossplane.io: true
    flows.authenticationflow.keycloak.crossplane.io: true
    executions.authenticationflow.keycloak.crossplane.io: true
    executionconfigs.authenticationflow.keycloak.crossplane.io: true
    bindings.authenticationflow.keycloak.crossplane.io: true

## cnpg
cluster:
  type: postgresql
  mode: standalone
  version:
    postgresql: "16"
  cluster:
    instances: 1
    postgresql:
      parameters:
        max_connections: "100"
    monitoring:
      enabled: true
    superuserSecret: cnpg-superuser-secret
    initdb:
      database: keycloak
      secret:
        name: cnpg-keycloak-secret
    roles:
    - name: keycloak
      ensure: present
      comment: keycloak-admin-user
      login: true
      inherit: true
      superuser: true
      createdb: true
      passwordSecret:
        name: cnpg-keycloak-secret
    annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      argocd.argoproj.io/sync-wave: "-1"
  backups:
    enabled: false
