apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-cip
spec:
  acme:
    email: support@suxess-it.com
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-staging-cip
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
