# applies to podtato-head-entry deployment only
ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
    external-dns.alpha.kubernetes.io/ttl: "60"
  hosts:
    - host: "{{ .Values.kubriXTeamName }}-${{values.application_id}}-test.{{ .Values.kubriXIngressDomain }}"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ingress-secret
      hosts:
        - "{{ .Values.kubriXTeamName }}-${{values.application_id}}-test.{{ .Values.kubriXIngressDomain }}"
