---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.deployment.service.name }}"
{{- if .Values.gardenercert.enabled }}
  annotations:
    cert.gardener.cloud/purpose: managed
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: {{ .Values.gardenercert.dnsnames }}
    dns.gardener.cloud/ttl: "180"
{{- end }}
{{- if not .Values.deployment.tls.name }}
  annotations:
    route.openshift.io/termination: edge   
{{- end }}
spec:
{{- if .Values.deployment.tls.name }}
  ingressClassName: nginx
  tls:
    - hosts:
        - "{{ .Values.deployment.ingress.host }}"
      secretName: "{{ .Values.deployment.tls.name }}"
{{- end }}
  rules:
    - host: "{{ .Values.deployment.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.deployment.service.name }}"
                port:
                  number: {{.Values.deployment.service.port}}
