cert:
  enabled: false

deployment:
  version: 1.3.3
  tls: 
    name: kubevirt-manager-server-tls
  ingress:
    host: kubevirt-manager.lab.suxessit.k8s.cloud.uibk.ac.at
    annotations:
      cert.gardener.cloud/purpose: managed
      dns.gardener.cloud/class: garden
      dns.gardener.cloud/dnsnames: kubevirt-manager.lab.suxessit.k8s.cloud.uibk.ac.at
      dns.gardener.cloud/ttl: "180"
    className: nginx
  service:
    name: kubevirt-manager
    port: 8080
