cert:
  enabled: false

deployment:
  version: 1.3.3
  tls: 
    name: kubevirt-manager-server-tls
  ingress:
    host: kubevirt-manager-127-0-0-1.nip.io
    annotations:
  service:
    name: kubevirt-manager
    port: 8080
