kyvernoPolicies:
- kargo-project-name-validation-apps-in-any-ns

kyverno:
  backgroundController:
    resources:
      limits:
        memory: 2Gi
  reportsController:
    resources:
      limits:
        memory: 2Gi