apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: grafana-kubrix-service-status
  namespace: mimir
  labels:
    platform: kubrix
    service: grafana
spec:
  groups:
  - name: kubrix.service.status
    interval: 30s
    rules:
    - record: kubrix_service_status
      labels:
        platform: kubrix
        service: grafana
      expr: |
        (
          2 * (scalar(min(probe_success{platform="kubrix",service="grafana"})) == bool 0)
        )
        +
        (
          scalar(
            max(
              kube_statefulset_status_replicas_available{namespace="grafana",statefulset="sx-grafana"}
              < bool
              kube_statefulset_replicas{namespace="grafana",statefulset="sx-grafana"}
            )
          )
          * (1 - (scalar(min(probe_success{platform="kubrix",service="grafana"})) == bool 0))
        )
