{{- $kubrix := default (dict) .Values.kubrix -}}
{{- $crossplane := default (dict) $kubrix.crossplane -}}
{{- $keycloak := default (dict) $crossplane.keycloak -}}
{{- $provider := default (dict) $keycloak.provider -}}
{{- $providerConfig := default (dict) $keycloak.providerConfig -}}
{{- $secretRef := default (dict) $providerConfig.secretRef -}}
{{- $replicas := default 1 $provider.replicas -}}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  package: {{ default "xpkg.upbound.io/crossplane-contrib/provider-keycloak:v2.19.0" $provider.package }}
  runtimeConfigRef:
    name: keycloak-provider-config
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: keycloak-provider-config
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  deploymentTemplate:
    spec:
      replicas: {{ $replicas }}
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: LEADER_ELECTION
                  value: "true"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  pkg.crossplane.io/provider: provider-keycloak
              matchLabelKeys:
                - pod-template-hash
---
apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ default "sx-keycloak-config" $providerConfig.name | quote }}
  namespace: {{ default "keycloak" $providerConfig.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: Secret
    secretRef:
      name: {{ default "keycloak-credentials" $secretRef.name }}
      key: {{ default "credentials" $secretRef.key }}
      namespace: {{ default "keycloak" $secretRef.namespace | quote }}
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: keycloak-mrap
spec:
  activate:
{{- $m := $keycloak.activeMRDs | default dict }}
{{- range $mrd, $enabled := $m }}
{{- if $enabled }}
    - {{ $mrd }}
{{- end }}
{{- end }}
