{{- if .Values.kubrixStatusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k8s-monitoring-kubrix-service-status
  namespace: mimir
  labels:
    platform: kubrix
    service: k8s-monitoring
spec:
  groups:
  - name: kubrix.service.status
    interval: 30s
    rules:
    - record: kubrix_service_status
      labels:
        platform: kubrix
        service: k8s-monitoring
      expr: |
        (
          2 * (scalar(min(probe_success{platform="kubrix",service="k8s-monitoring"})) == bool 0)
        )
        +
        (
          scalar(max(GRAFANA_ALERTS{namespace="k8s-monitoring"} == bool 1) or vector(0))
          *
          (1 - (scalar(min(probe_success{platform="kubrix",service="k8s-monitoring"})) == bool 0))
        )
{{- end }}