# this one for local kind cluster vault->keycloak
{{- if contains "nip.io" .Values.eso.oidcDiscoveryUrl }}
apiVersion: v1
kind: Service
metadata:
  name: "kc-service-vault"
  labels:
    app: "keycloak-service"
spec:
  ports:
  - name: "keycloak-service"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: "keycloak-service"
  type: ClusterIP
{{- end }}