mimir:
  global:
    dnsService: coredns
    dnsNamespace: openshift-dns
  nginx:
    ingress:
      enabled: true
      annotations:
        route.openshift.io/termination: edge   
        cert-manager.io/cluster-issuer: letsencrypt-staging-open
      hosts:
        - host: metrics-monitoring.apps.cluster1.mcp.pitagora.at
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: mimir-nginx-tls
          hosts:
            - metrics-monitoring.apps.cluster1.mcp.pitagora.at
  mimir:
    structuredConfig:
      limits:
        max_global_series_per_user: 500000
  distributor:
    resources:
      limits:
        cpu: 3.5
        memory: 6Gi
  ingester:
    resources:
      limits:
        cpu: 5
        memory: 12Gi
    persistentVolume:
      size: 50Gi
  minio:
    persistence:
      size: 100Gi
