kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
data:
  rbac-policy.csv: |
    {{- range $name, $lines := .Values.rbac.policies }}
    {{- if $lines }}
    {{ $lines | trim | nindent 4 }}
    {{- end }}
    {{- end }}