apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: backstage-vault
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-3"
spec:
  providerConfigRef:
    name: openbao-crossplane-providerconfig
  forProvider:
    name: backstage-vault
    policy: |
      path "kubrix-kv/*" {
        capabilities = ["create", "read", "update", "delete", "list"]
      }
---
# Kubernetes auth role - Backstage pod (default SA, backstage namespace) authenticates
apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-3"
  name: backstage-vault-kubernetes
spec:
  providerConfigRef:
    name: openbao-crossplane-providerconfig
  forProvider:
    backend: kubernetes
    boundServiceAccountNames:
      - default
    boundServiceAccountNamespaces:
      - backstage
    roleName: backstage-vault
    tokenPolicies:
      - backstage-vault
    tokenTtl: 300