teams:
# new team stanza for team kubrix
  - name: kubrix
    sourceRepos:
      - 'https://github.com/kubriX-demo/kubrix-a2748-*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/kubriX-demo/kubrix-a2748-apps
      path: .
      revision: main
    multiStageKargoAppSet:
      github:
        organization: kubriX-demo
    ## prime-only
    # previewEnvironmentsDefaults:
    #  enabled: true
    #  labels:
    #    - preview
    #  requeueAfterSeconds: 60
    #  valuesFiles:
    #    - values-preview.yaml
    #admins:
    #  - adminuser
    #editors:
    #  - editoruser
    #viewers:
    #  - vieweruser
    ## end prime-only
