vui:
  global:
    veleroNamespace: velero
    kubernetesClusterDomain: cluster.local
    clusterName: "suxessit--lab"

  apiConfig:
    apiEnableDocumentation: "1"
    k8SInClusterMode: "True"
    origins1: 'https://velero-ui.apps.cluster1.mcp.pitagora.at'
    veleroCliVersion: v1.14.0
    existingSecret: velero-ui-credential

  uiIngress:
    enabled: true
    host: velero-ui.apps.cluster1.mcp.pitagora.at
    metadata:
      annotations:
        route.openshift.io/termination: edge   
  uiNp: # NodePort
    enabled: false
    ip: ""
    apiPort: "30001"
    uiPort: "30002"

