nginxIngressClass:
  enabled: true

traefik:
  ingressClass:
    name: "traefik"

  providers:
    kubernetesIngressNGINX:
      enabled: true
      publishService:
        enabled: true

  accessLog:
    enabled: true
    format: json
