nginxIngressClass:
  enabled: true

traefik:
  ingressClass:
    name: "traefik"

  providers:
    kubernetesIngressNginx:
      enabled: true
      publishService:
        enabled: true

  logs:
    access:
      enabled: true
      format: json
