falco:
  scc:
    create: false

  tty: true

  driver:
    enabled: true
    kind: kmod
  #  loader:
  #    initContainer:
  #      image:
  #        repository: falcosecurity/falco-driver-loader-legacy
    #kind: modern-bpf
    kubernetes:
      enabled: true

  falco:
    json_output: true
    json_include_output_property: true
    log_syslog: false
    log_level: info

    grpc_output:
      enabled: true
      bind_address: "unix:///run/falco/falco.sock"
      threadiness: 0

  falcosidekick:
    enabled: true
    webui:
      enabled: true
      replicaCount: 1
      ingress:
        enabled: true
        annotations:
          route.openshift.io/termination: edge   
          cert-manager.io/cluster-issuer: letsencrypt-prod-open
        hosts:
          - host: falco.apps.cluster1.mcp.pitagora.at
            paths:
              - path: /
                pathType: Prefix
        tls:
            - secretName: falco-server-tls
              hosts:
                - falco.apps.cluster1.mcp.pitagora.at
    replicaCount: 1
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: true
    config:
      loki:
        hostport: "http://sx-loki.loki.svc.cluster.local:3100"

falco-exporter:
  falco:
    grpcUnixSocketPath: "unix:///run/falco/falco.sock"
    grpcTimeout: 3m

  serviceMonitor:
    enabled: true
  grafanaDashboard:
    enabled: true
    namespace: falco

  prometheusRules:
    enabled: true

k8s-metacollector:
  serviceMonitor:
    create: true
  grafana:
    dashboards:
      enabled: true
      configMaps:
        collector:
          name: k8s-metacollector-grafana-dashboard
          namespace: "falco"
