apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.deployments.keycloak.service.name }}"
  {{- with .Values.deployments.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  {{- if .Values.deployments.ingress.className }}
  ingressClassName: {{ .Values.deployments.ingress.className | quote }}
  {{- end }}
  {{- if .Values.secrets.tls.name }}
  tls:
    - hosts:
        - "keycloak{{ .Values.deployments.ingress.fqdn }}"
      secretName: "{{ .Values.secrets.tls.name }}"
  {{- end }}
  rules:
    - host: "keycloak{{ .Values.deployments.ingress.fqdn }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.deployments.keycloak.service.name }}"
                port:
                  number: {{.Values.deployments.keycloak.ports.containerPort}}
