letsEncryptProdClusterIssuer:
  enabled: true
  default: true

solvers:
  - http01:
      ingress:
        ingressClassName: nginx

cert-manager:
  prometheus:
    enabled: true
  servicemonitor:
    enabled: true