kubernetesAlerts:
  platformTeamContactPoint:
    receivers:
      # please change this!
      - uid: platform-team-default
        type: prometheus-alertmanager
        disableResolveMessage: false
        settings:
          url: http://test:9000
