kubernetesAlerts:
  platformTeamContactPoint:
    receivers:
      - uid: platform-team-default
        type: teams
        settings:
          url: https://myteams-url.com
        disableResolveMessage: false
# example:
#      - uid: platform-team-default
#        type: teams
#        settings:
#          url: https://myteams-url.com
#        disableResolveMessage: false

