{
 "title": "Hashicorp Vault Dashboard",
 "description": "Hashicorp Vault Metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5m" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "License Expiration (${datasource})",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time:YYYY-MM-DD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_core_license_expiration_time_epoch)*1000"
    }
   ]
  },
  {
   "title": "Time passed since last successful snapshot",
   "type": "bargauge",
   "description": "Time passed since the last successful snapshot was taken.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vault_autosnapshots_last_success_time{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timestamp of the last successful snapshot",
   "type": "stat",
   "description": "Timestamp of the last successful snapshot taken.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_autosnapshots_last_success_time{}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Cluster Health (${datasource})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "targets": [
    { "expr": "vault_autopilot_healthy" }
   ]
  },
  {
   "title": "Failure Tolerance (${datasource})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "vault_autopilot_failure_tolerance"
    }
   ]
  },
  {
   "title": "Cluster Health per Node (${datasource})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "vault_autopilot_node_healthy" }
   ]
  },
  {
   "type": "text",
   "description": "Click to open system and infrastructure logs of the cluster.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DR Status (vault-nonprod)",
   "type": "stat",
   "description": "Status of cluster in DR, Primary, Secondary or undefined",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Last DR and remote DR WAL indexes from both clusters over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "vault_replication_wal_last_dr_wal unless vault_replication_fsm_last_remote_wal or vault_replication_fsm_last_remote_wal",
     "legendFormat": "DR WAL INDEX (vault-nonprod)"
    },
    {
     "expr": "vault_replication_wal_last_dr_wal unless vault_replication_fsm_last_remote_wal or vault_replication_fsm_last_remote_wal",
     "legendFormat": "DR WAL INDEX (vault-nonprod-dr)"
    }
   ]
  },
  {
   "title": "DR Status (vault-nonprod-dr)",
   "type": "stat",
   "description": "Status of cluster in DR, Primary, Secondary or undefined",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "DR WAL INDEX (vault-nonprod)",
   "type": "stat",
   "description": "Either the last DR WAL index of the primary or the last index from the primary the secondary cluster wrote. Metric only collected on vault-nonprod cluster nodes.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_replication_wal_last_dr_wal unless vault_replication_fsm_last_remote_wal or vault_replication_fsm_last_remote_wal",
     "legendFormat": "DR WAL INDEX (vault-nonprod)"
    }
   ]
  },
  {
   "title": "DR WAL INDEX (vault-nonprod-dr)",
   "type": "stat",
   "description": "Either the last DR WAL index of the primary or the last index from the primary the secondary cluster wrote. Metric only collected on ${datasource} cluster nodes.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_replication_wal_last_dr_wal unless vault_replication_fsm_last_remote_wal or vault_replication_fsm_last_remote_wal",
     "legendFormat": "DR WAL INDEX (vault-nonprod-dr)"
    }
   ]
  },
  {
   "title": "WAL INDEX (vault-nonprod)",
   "type": "stat",
   "description": "The last WAL index of the primary cluster. Metric only collected on vault-nonprod cluster nodes.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_replication_wal_last_wal", "legendFormat": "WAL INDEX (vault-nonprod)" }
   ]
  },
  {
   "title": "WAL INDEX (vault-nonprod-dr)",
   "type": "stat",
   "description": "The last WAL index written. Metric only collected on vault-nonprod-dr cluster nodes.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_replication_wal_last_wal", "legendFormat": "WAL INDEX (vault-nonprod-dr)" }
   ]
  },
  {
   "title": "Leases (${datasource})",
   "type": "stat",
   "description": "Number of Leases across namespaces",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "Average Login Time (${datasource})",
   "type": "stat",
   "description": "Average time to login (ms)",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vault_core_handle_login_request_sum[$interval]) / rate(vault_core_handle_login_request_count[$interval]))"
    }
   ]
  },
  {
   "title": "Log Request Failures (${datasource})",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure[$interval]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Requests (req/s) (${datasource})",
   "type": "timeseries",
   "description": "Average core and log request handlers",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(vault_audit_log_request_sum[$__interval])/rate(vault_audit_log_request_count[$__interval])",
     "legendFormat": "Audit Request"
    },
    {
     "expr": "rate(vault_audit_log_response_sum[$__interval])/rate(vault_audit_log_response_count[$__interval])",
     "legendFormat": "Audit Response"
    },
    {
     "expr": "rate(vault_core_handle_request_sum[$__interval])/rate(vault_core_handle_request_count[$__interval])",
     "legendFormat": "Handled by Vault Core"
    }
   ]
  },
  {
   "title": "KV Engines (${datasource})",
   "type": "stat",
   "description": "Number of KV Engines across namespaces",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vault_secret_kv_count)" }
   ]
  },
  {
   "title": "Authentication Rate (${datasource})",
   "type": "timeseries",
   "description": "Rate of Authentication Requests",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(vault_core_handle_login_request_count[$interval]))"
    }
   ]
  },
  {
   "title": "Log Response Failures (${datasource})",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure[$interval]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Identity (${datasource})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Entities (${datasource})",
     "type": "stat",
     "description": "Number of Entities across namespaces",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vault_identity_num_entities)"
      }
     ]
    },
    {
     "title": "Entity Aliases (${datasource})",
     "type": "stat",
     "description": "Number of Entity Aliases across namespaces",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vault_identity_entity_alias_count)"
      }
     ]
    },
    {
     "title": "Entity Count by Namespace (${datasource})",
     "type": "table",
     "description": "Entity Count by Namespace",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum by (namespace) (vault_identity_entity_count)"
      }
     ]
    },
    {
     "title": "Entity Aliases by Method (${datasource})",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without(instance) (vault_identity_entity_alias_count)",
       "legendFormat": "{{ auth_method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Token (${datasource})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Available Tokens (${datasource})",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(vault_token_count)" }
     ]
    },
    {
     "title": "Pending Tokens (${datasource})",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(vault_token_create_count - vault_token_store_count)"
      }
     ]
    },
    {
     "title": "Tokens by TTL (${datasource})",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_ttl)",
       "legendFormat": "{{ creation_ttl }}"
      }
     ]
    },
    {
     "title": "Tokens by Namespace (${datasource})",
     "type": "table",
     "description": "Token Count by Namespace",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "sum without(instance) (vault_token_count)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Token Lookups (${datasource})",
     "type": "timeseries",
     "description": "Token Lookup Rate",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(vault_token_lookup_count[$interval])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Tokens by Policy (${datasource})",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_policy)",
       "legendFormat": "{{ policy }}"
      }
     ]
    },
    {
     "title": "Tokens by Auth Method (${datasource})",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_auth)",
       "legendFormat": "{{ auth_method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy (${datasource})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Policy Set (${datasource})",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(vault_policy_set_policy_count[1m]))",
       "legendFormat": "SET"
      }
     ]
    },
    {
     "title": "Policy Get (${datasource})",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(vault_policy_get_policy_count[1m]))",
       "legendFormat": "GET"
      }
     ]
    }
   ]
  },
  {
   "title": "Vault and Raft Leadership (${datasource})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Vault Leadership Lost Count (${datasource})",
     "type": "stat",
     "description": "Any count greater than zero means that Vault experienced a leadership change.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "vault_core_leadership_lost_count"
      }
     ]
    },
    {
     "title": "Current Leader (${datasource})",
     "type": "stat",
     "description": "Last reported Vault and Raft leader node",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "vault_raft_state_leader", "legendFormat": "{{ host }}" }
     ]
    },
    {
     "title": "Vault Raft Leader Elections (${datasource})",
     "type": "stat",
     "description": "Increments whenever raft server starts an election. If there are frequent elections or leadership changes, it would likely indicate network issues between the raft nodes, or that the raft servers themselves are unable to keep up with the load.",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(vault_raft_state_candidate)"
      }
     ]
    },
    {
     "title": "Raft Leader Last Contact (ms) (${datasource})",
     "type": "timeseries",
     "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_leader_lastContact_sum[$interval]) / rate(vault_raft_leader_lastContact_count[$interval]))"
      }
     ]
    },
    {
     "title": "Vault Leadership Setup Failures (${datasource})",
     "type": "stat",
     "description": "Number of Vault cluster leadership setup failures. Failures indicate bad overall cluster leadership status.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "vault_core_leadership_setup_failed"
      }
     ]
    },
    {
     "title": "Raft Follower State Entered Count (${datasource})",
     "type": "bargauge",
     "description": "Number of times node has entered the follower mode. This happens when a new node joins the cluster or after the end of a leader election.",
     "gridPos": { "h": 3, "w": 8, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      { "expr": "vault_raft_state_follower", "legendFormat": "{{ host }}" }
     ]
    }
   ]
  },
  {
   "title": "Raft Integrated Storage Performance (${datasource})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Storage Performance (ms) (${datasource})",
     "type": "timeseries",
     "description": "Performance of Raft Integrated Storage Backend",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_storage_delete_sum[$interval]) / rate(vault_raft_storage_delete_count[$interval]))",
       "legendFormat": "AVG DEL"
      },
      {
       "expr": "sum(rate(vault_raft_storage_list_sum[$interval]) / rate(vault_raft_storage_list_count[$interval]))",
       "legendFormat": "AVG LIST"
      },
      {
       "expr": "sum(rate(vault_raft_storage_get_sum[$interval]) / rate(vault_raft_storage_get_count[$interval]))",
       "legendFormat": "AVG GET"
      },
      {
       "expr": "sum(rate(vault_raft_storage_put_sum[$interval]) / rate(vault_raft_storage_put_count[$interval]))",
       "legendFormat": "AVG PUT"
      }
     ]
    },
    {
     "title": "Time Spent (ms) (${datasource})",
     "type": "bargauge",
     "description": "Sum of time spent to perform actions on the storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(vault_raft_storage_delete_sum)",
       "legendFormat": "DEL"
      },
      {
       "expr": "sum(vault_raft_storage_list_sum)",
       "legendFormat": "LIST"
      },
      {
       "expr": "sum(vault_raft_storage_get_sum)",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(vault_raft_storage_put_sum)",
       "legendFormat": "PUT"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/Mem Info (${datasource})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Objects Used (${datasource})",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{} / vault_runtime_malloc_count{})"
    }
   ]
  },
  {
   "title": "Number of Goroutines (${datasource})",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{})"
    }
   ]
  },
  {
   "title": "Allocated MB (${datasource})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{})"
    }
   ]
  }
 ]
}