{
 "title": "Hashicorp Vault",
 "description": " Hashicorp Vault Metrics",
 "tags": [
  "vault",
  "suXess"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(up{job=\"sx-vault-active\"},instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(up{job=\"sx-vault-active\", instance=~\"$node:(.*)\"},instance)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": "label_values(vault_secret_kv_count, mount_point)"
   },
   { "name": "interval", "label": "Interval", "query": "5m" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"sx-vault-active\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(1 + vault_core_unsealed{})", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "KV Engines",
   "type": "stat",
   "description": "Number of KV Engines across namespaces",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vault_secret_kv_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities)"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vault_identity_entity_alias_count)",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Overall Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "vault_autopilot_healthy", "legendFormat": "healthy" }
   ]
  },
  {
   "title": "Cluster Health per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "vault_autopilot_node_healthy", "legendFormat": "healthy" }
   ]
  },
  {
   "title": "Failure Tolerance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "vault_autopilot_failure_tolerance",
     "legendFormat": "failure tolerance"
    }
   ]
  },
  {
   "title": "Entitiy Count by Namespace (${datasource})",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (namespace) (vault_identity_entity_count)"
    }
   ]
  },
  {
   "title": "Entitiy Count by Method (${datasource})",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "avg without(instance)(vault_identity_entity_alias_count)"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_secret_kv_count)",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Vault and Raft Leadership",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vault Leadership Lost Count",
     "type": "stat",
     "description": "Any count greater than zero means that Vault experienced a leadership change.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "vault_core_leadership_lost_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vault Leadership Setup Failures",
     "type": "stat",
     "description": "Number of Vault cluster leadership setup failures. Failures indicate bad overall cluster leadership status.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "vault_core_leadership_setup_failed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Leader",
     "type": "stat",
     "description": "Last reported Vault and Raft leader node",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "vault_raft_state_leader", "legendFormat": "{{ host }}" }
     ]
    },
    {
     "title": "Vault Raft Leader Elections",
     "type": "stat",
     "description": "Increments whenever raft server starts an election. If there are frequent elections or leadership changes, it would likely indicate network issues between the raft nodes, or that the raft servers themselves are unable to keep up with the load.",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(vault_raft_state_candidate)",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Raft Follower State Entered Count ",
     "type": "bargauge",
     "description": "Number of times node has entered the follower mode. This happens when a new node joins the cluster or after the end of a leader election.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      { "expr": "vault_raft_state_follower", "legendFormat": "{{ host }}" }
     ]
    },
    {
     "title": "Raft Leader Last Contact (ms)",
     "type": "timeseries",
     "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_leader_lastContact_sum[$interval]) / rate(vault_raft_leader_lastContact_count[$interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Raft Integrated Storage Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Performance (ms) (${datasource})",
     "type": "timeseries",
     "description": "Performance of Raft Integrated Storage Backend",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_storage_delete_sum[$interval]) / rate(vault_raft_storage_delete_count[$interval]))",
       "legendFormat": "AVG DEL"
      },
      {
       "expr": "sum(rate(vault_raft_storage_list_sum[$interval]) / rate(vault_raft_storage_list_count[$interval]))",
       "legendFormat": "AVG LIST"
      },
      {
       "expr": "sum(rate(vault_raft_storage_get_sum[$interval]) / rate(vault_raft_storage_get_count[$interval]))",
       "legendFormat": "AVG GET"
      },
      {
       "expr": "sum(rate(vault_raft_storage_put_sum[$interval]) / rate(vault_raft_storage_put_count[$interval]))",
       "legendFormat": "AVG PUT"
      }
     ]
    },
    {
     "title": "Time Spent (ms) (${datasource})",
     "type": "bargauge",
     "description": "Sum of time spent to perform actions on the storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(vault_raft_storage_delete_sum)",
       "legendFormat": "DEL"
      },
      {
       "expr": "sum(vault_raft_storage_list_sum)",
       "legendFormat": "LIST"
      },
      {
       "expr": "sum(vault_raft_storage_get_sum)",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(vault_raft_storage_put_sum)",
       "legendFormat": "PUT"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/Mem Info: $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap Objects Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_heap_objects{} / vault_runtime_malloc_count{})"
      }
     ]
    },
    {
     "title": "Number of Goroutines",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_num_goroutines{})"
      }
     ]
    },
    {
     "title": "Allocated MB",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(vault_runtime_alloc_bytes{})",
       "legendFormat": "$node"
      }
     ]
    }
   ]
  },
  {
   "title": "Token",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Available Tokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "avg(vault_token_count)" }
     ]
    },
    {
     "title": "Tokens by Policy",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 41 },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_policy)",
       "legendFormat": "{{ policy }}"
      }
     ]
    },
    {
     "title": "Pending Tokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_token_create_count - vault_token_store_count)"
      }
     ]
    },
    {
     "title": "Tokens by TTL",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_ttl)",
       "legendFormat": "{{ creation_ttl }}"
      }
     ]
    },
    {
     "title": "Tokens by Auth Method",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_auth)",
       "legendFormat": "{{ auth_method }}"
      }
     ]
    },
    {
     "title": "Tokens Creation by Method & TTL",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(auth_method, creation_ttl) (vault_token_creation)",
       "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
      }
     ]
    },
    {
     "title": "Token Creation/Storage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_create_count)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg without(instance) (vault_token_store_count)",
       "legendFormat": "Store"
      }
     ]
    },
    {
     "title": "Token Lookups",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_token_lookup_count[1m]))",
       "legendFormat": "Lookups"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Log Request Failures",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 124 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_request_failure[1m]))",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Log Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 3, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_audit_log_request_count[1m]))",
       "legendFormat": "Request "
      },
      {
       "expr": "avg(irate(vault_audit_log_response_count[1m]))",
       "legendFormat": "Response"
      },
      {
       "expr": "avg(irate(vault_core_handle_request_count[1m]))",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "Consul Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_consul_get_count[1m]))",
       "legendFormat": "GET"
      },
      {
       "expr": "avg(irate(vault_consul_put_count[1m]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "avg(irate(vault_consul_delete_count[1m]))",
       "legendFormat": "DELETE"
      },
      {
       "expr": "irate(vault_consul_list_count{instance=\"$node:$port\"}[1m])",
       "legendFormat": "LIST"
      }
     ]
    },
    {
     "title": "Log Response Failures",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 129 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_response_failure[1m]))",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Policy Set",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_policy_set_policy_count[1m]))",
       "legendFormat": "SET"
      }
     ]
    },
    {
     "title": "Policy Get",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_policy_get_policy_count[1m]))",
       "legendFormat": "GET"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "mountpoint",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      },
      {
       "expr": "avg(rate(vault_route_rollback_${mountpoint}__sum[1m]) / rate(vault_route_rollback_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Rollback"
      }
     ]
    }
   ]
  }
 ]
}