{{- if eq (default false .Values.pgadmin4.enabled) true }}
{{- $fullHost := "" }}
{{- if and .Values.pgadmin4.ingress.tls (gt (len .Values.pgadmin4.ingress.tls) 0) }}
  {{- $tlsEntry := index .Values.pgadmin4.ingress.tls 0 }}
  {{- if and $tlsEntry.hosts (gt (len $tlsEntry.hosts) 0) }}
    {{- $fullHost = index $tlsEntry.hosts 0 }}
  {{- end }}
{{- else if and .Values.pgadmin4.ingress.hosts (gt (len .Values.pgadmin4.ingress.hosts) 0) }}
  {{- $fullHost = (index .Values.pgadmin4.ingress.hosts 0).host }}
{{- end }}
{{- if $fullHost }}
{{- $domainName := regexReplaceAll "^[^.]+\\." $fullHost "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadminconfiglocal
  namespace: cnpg
data:
  config_local.py: |+
    import os
    import logging

    FILE_LOG_LEVEL = logging.INFO
    SERVER_MODE = True
    CONSOLE_LOG_LEVEL = logging.INFO
    MASTER_PASSWORD_REQUIRED = True
    AUTHENTICATION_SOURCES = ['internal', 'oauth2']
{{- if .Values.pgadmin4.disableOauth2SslCertVerification }}
    OAUTH2_SSL_CERT_VERIFICATION = False
{{- end }}
    OAUTH2_CONFIG = [
      {
        'OAUTH2_NAME': 'keycloak',
        'OAUTH2_DISPLAY_NAME': 'keycloak',
        'OAUTH2_CLIENT_ID': os.environ['pgadminclientid'],
        'OAUTH2_CLIENT_SECRET': os.environ['pgadminclientsecret'],
        'OAUTH2_TOKEN_URL': 'https://keycloak.{{ $domainName }}/realms/kubrix/protocol/openid-connect/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://keycloak.{{ $domainName }}/realms/kubrix/protocol/openid-connect/auth',
        'OAUTH2_API_BASE_URL': 'https://keycloak.{{ $domainName }}/',
        'OAUTH2_USERINFO_ENDPOINT': 'https://keycloak.{{ $domainName }}/realms/kubrix/protocol/openid-connect/userinfo',
        'OAUTH2_SCOPE': 'openid groups email profile',
        'OAUTH2_SERVER_METADATA_URL': 'https://keycloak.{{ $domainName }}/realms/kubrix/.well-known/openid-configuration',
        'OAUTH2_LOGOUT_URL': 'https://keycloak.{{ $domainName }}/realms/kubrix/protocol/openid-connect/logout?client_id=pgadmin',
        "OAUTH2_BUTTON_COLOR": "None", "OAUTH2_ICON": "None" 
      }
    ]
{{- end }}
{{- end }}