on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/kube-score.yaml'
      - '.github/kube-score.sh'
      - 'platform-apps/charts/**'
      
permissions:
  contents: read
  pull-requests: read

name: kube-score

jobs:
  kube-score:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(vars.GITOPS_DIFF_TESTCASES) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - id: filter
        uses: dorny/paths-filter@v4
        with:
          list-files: json
          # For PRs it compares base..head. For push it compares before..after.
          filters: |
            appChanges:
              - 'platform-apps/charts/**'
            globalChanges:
               - '.github/workflows/kube-score.yaml'
               - '.github/kube-score.sh'


      - name: kube-score charts
        shell: bash
        env:
          CHANGED_APPS: ${{ steps.filter.outputs.appChanges_files }}
        run: |
          .github/kube-score.sh ${{ matrix.testCase }} ${{ matrix.valuesFiles }} "${{ matrix.setValues }}"
